### ISSUE TITLE
ODBC Driver под .NET

### ISSUE THREAD

**Issue by denis-ivanov** [yandex/clickhouse-odbc#64]
Собрал драйвер под Ubuntu от коммита e062efee13c67f1d4cc56a2e78ad37db8867ed60
Далее создал простой проект в Rider со следующим кодом:

```csharp
using System;
using System.Data.Odbc;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var builder = new OdbcConnectionStringBuilder();
            builder.Driver = "/home/denis/sources/clickhouse-odbc/build/driver/libclickhouseodbc.so";
            builder.Add("SERVER", "localhost");
            builder.Add("DATABASE", "default");
            builder.Add("PORT", 8123);
            builder.Add("FRAMED", 0);
            var connection = new OdbcConnection(builder.ConnectionString);
            connection.Open();

            Console.WriteLine(connection.ServerVersion);

            var command = connection.CreateCommand();
            command.CommandText = "select 1";

            var reader = command.ExecuteReader();
            
            connection.Close();
        }
    }
}
```

Получаю ошибку:
```
/usr/share/dotnet/dotnet /home/denis/RiderProjects/ConsoleApp1/ConsoleApp1/bin/Debug/netcoreapp2.0/ConsoleApp1.dll
01.00.0000

Unhandled Exception: System.Data.Odbc.OdbcException: ERROR [HY000] HTTP status code: 500
Received error:
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 9: 
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader, Object[] methodArguments, SQL_API odbcApiMethod)
   at ConsoleApp1.Program.Main(String[] args) in /home/denis/RiderProjects/ConsoleApp1/ConsoleApp1/Program.cs:line 24
```

**Comment by proller** [comment]
А что в логе сервера про эту ошибку?
И какой запрос дошел до сервера?
обычно после failed at position 9:  идет подробное описание ошибки.

**Comment by denis-ivanov** [comment]
Извиняюсь, что так долго отвечал, собрал снова драйвер. 
```csharp
[TestFixture]
    public class OdbcConnectionTests
    {
        [Test]
        public void SelectOne()
        {
            var stringBuilder = new OdbcConnectionStringBuilder
            {
                Driver = "/home/denis/dev/clickhouse-odbc/build/driver/libclickhouseodbc.so"
            };
            
            stringBuilder.Add("url", "http://172.17.0.2");

            using (var connection = new OdbcConnection(stringBuilder.ConnectionString))
            using (var command = connection.CreateCommand())
            {
                command.CommandText = "SELECT 1";
                connection.Open();

                using (var reader = command.ExecuteReader())
                {
                    Assert.IsTrue(reader.Read());
                    var theOne = reader.GetInt32(0);
                    Assert.AreEqual(1, theOne);
                }
            }
        }
    }
```

Test output:
```
System.Data.Odbc.OdbcException : ERROR [HY000] HTTP status code: 400
Received error:
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 9: 
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader, Object[] methodArguments, SQL_API odbcApiMethod)
```

```bash
cat /var/log/clickhouse-server/clickhouse-server.err.log
```

```
2019.02.02 18:04:11.141973 [ 21 ] {} <Error> HTTPHandler: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 9: . Unrecognized token, e.what() = DB::Exception, Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x9fde646]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x3317a42]
2. /usr/bin/clickhouse-server(DB::parseQuery(DB::IParser&, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)+0xac) [0x7808d1c]
3. /usr/bin/clickhouse-server() [0x70666ca]
4. /usr/bin/clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)+0xca) [0x706880a]
5. /usr/bin/clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x3419) [0x33341e9]
6. /usr/bin/clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x3be) [0x333668e]
7. /usr/bin/clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x332) [0xa08fe02]
8. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0xa0886af]
9. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x16a) [0xa088a8a]
10. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x77) [0xa6d2037]
11. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0xa6cdef8]
12. /usr/bin/clickhouse-server() [0xaa3e73f]
13. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f56eacdc6db]
14. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f56ea25b88f]
```

**Comment by denis-ivanov** [comment]
ClickHouse в docker.

**Comment by denis-ivanov** [comment]
Собственно та же проблема #137.
